#!/usr/bin/env python3

# Created by: Lily Carroll
# Created on: Oct/17/2023
# This program allows for the generation of random numbers. The user can input a guess and my program will tell them if they got it right or wrong.
# Importing the random generator from the python modules.
import random


def main():
    # Declaring my variable for the random number generated by my program.
    random_number = random.randint(1, 17)

    # Getting the user input for their guess.
    user_guess = int(input("Enter a number between 1-17 for your guess: "))

    # Using If...Then...Else statements to determine if the user's guess is correct or incorrect.
    if user_guess == random_number:
        print("You guessed correctly. The number is {}.".format(random_number))

    else:
        print("You guessed wrong. The correct number was {}.".format(random_number))


if __name__ == "__main__":
    main()
